IF 1 = 1 THEN PRINT "true"
PRAGMA PRINTED "true\n"

IF 1 = 2 THEN PRINT "false"
PRAGMA PRINTED ""

PRINT "ok"
PRAGMA PRINTED "ok\n"

IF 1 = 2 THEN PRINT "false" ELSE PRINT "true"
IF 1 = 1 THEN PRINT "true" ELSE PRINT "false"
PRAGMA PRINTED "true\ntrue\n"

REM IF 1 = 2 THEN
REM    PRINT "true"
REM ELSE
REM    PRINT "false"
REM END IF
REM PRAGMA PRINTED "false\n"

REM LET a% = 1 + 1
REM LET b# = 2
REM IF a% = b# THEN PRINT "true"
REM PRAGMA PRINTED "true\n"

REM PRINT a% = b#
REM PRINT a% <> b#
REM PRAGMA PRINTED "-1\n0\n"
