# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "1220bdedf1a993d852d8aebcd63922a8fb163fac37b9c6ff72d187b2847a4a3a4248";
    path = fetchzip {
      url = "https://github.com/ikskuh/zig-args/archive/968258dc1b1230493d8f1677097c832a3d7e0bd8.tar.gz";
      hash = "sha256-YW2edEIZSx+aldYa4X4VfRxyXCUHwX+It1Oq6zNGsWU=";
    };
  }
]
